name: 🚀 Deploy website on push

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the Network's Graph
        run: |
          python parse_roam.py --hugo .

      - name: Build
        run: hugo --gc --minify --verbose

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: ./public/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
